framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/default_translations'
        providers:
