Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "user-management"
        v.customize ["modifyvm", :id, "--memory", 2048]
    end

    config.vm.box = "debian/stretch64"
    config.vm.network :private_network, ip: "192.168.33.99"
    config.ssh.forward_agent = true
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.synced_folder "../", "/vagrant", id: "vagrant-root", :nfs => true
end
