# StartController

index:
    path:     /{_locale}/
    controller: App\Controller\StartController::indexAction
    requirements:
        _locale: '%locales%'

aliases:
    path:     /{_locale}/alias
    controller: App\Controller\StartController::aliasAction
    requirements:
        _locale: '%locales%'

openpgp:
    path:     /{_locale}/openpgp
    controller: App\Controller\StartController::openPgpAction
    requirements:
        _locale: '%locales%'

vouchers:
    path:     /{_locale}/voucher
    controller: App\Controller\StartController::voucherAction
    requirements:
        _locale: '%locales%'

account:
    path:     /{_locale}/account
    controller: App\Controller\StartController::accountAction
    requirements:
        _locale: '%locales%'

# DeleteController

alias_delete:
    path:     /{_locale}/alias/delete/{aliasId}
    controller: App\Controller\DeleteController::deleteAliasAction
    requirements:
        _locale: '%locales%'

user_delete:
    path:     /{_locale}/user/delete
    controller: App\Controller\DeleteController::deleteUserAction
    requirements:
        _locale: '%locales%'

openpgp_delete:
    path:     /{_locale}/openpgp/delete
    controller: App\Controller\DeleteController::deleteOpenPgpAction
    requirements:
        _locale: '%locales%'

# RegistrationController

register:
    path:     /{_locale}/register
    controller: App\Controller\RegistrationController::registerAction
    requirements:
        _locale: '%locales%'

register_recovery_token:
    path:     /{_locale}/register/recovery_token
    controller: App\Controller\RegistrationController::registerRecoveryTokenAckAction
    requirements:
        _locale: '%locales%'

register_welcome:
    path:     /{_locale}/register/welcome
    controller: App\Controller\RegistrationController::welcomeAction
    requirements:
        _locale: '%locales%'

register_voucher:
    path:     /{_locale}/register/{voucher}
    controller: App\Controller\RegistrationController::registerAction
    requirements:
        _locale: '%locales%'

# RecoveryController

recovery:
    path:     /{_locale}/recovery
    controller: App\Controller\RecoveryController::recoveryProcessAction
    requirements:
        _locale: '%locales%'

recovery_reset_password:
    path:     /{_locale}/recovery/reset_password
    controller: App\Controller\RecoveryController::recoveryResetPasswordAction
    requirements:
        _locale: '%locales%'

recovery_recovery_token_ack:
    path:     /{_locale}/recovery/recovery_token/ack
    controller: App\Controller\RecoveryController::recoveryRecoveryTokenAckAction
    requirements:
        _locale: '%locales%'

user_recovery_token:
    path:     /{_locale}/user/recovery_token
    controller: App\Controller\RecoveryController::recoveryTokenAction
    requirements:
        _locale: '%locales%'

user_recovery_token_ack:
    path:     /{_locale}/user/recovery_token/ack
    controller: App\Controller\RecoveryController::recoveryTokenAckAction
    requirements:
        _locale: '%locales%'

# TwofactorController

user_twofactor:
    path:     /{_locale}/user/twofactor
    controller: App\Controller\TwofactorController::twofactorAction
    requirements:
        _locale: '%locales%'

user_twofactor_confirm:
    path:     /{_locale}/user/twofactor_confirm
    controller: App\Controller\TwofactorController::twofactorConfirmAction
    requirements:
        _locale: '%locales%'

user_twofactor_backup_ack:
    path:     /{_locale}/user/twofactor_backup_codes
    controller: App\Controller\TwofactorController::twofactorBackupAckAction
    requirements:
        _locale: '%locales%'

user_twofactor_disable:
    path:     /{_locale}/user/twofactor_disable
    controller: App\Controller\TwofactorController::twofactorDisableAction
    requirements:
        _locale: '%locales%'

user_twofactor_qrcode:
    path:     /{_locale}/user/twofactor/qrcode
    controller: App\Controller\TwofactorController::displayTotpQrCode
    requirements:
        _locale: '%locales%'

## InitController

init:
    path:     /{_locale}/init
    controller: App\Controller\InitController::indexAction
    requirements:
        _locale: '%locales%'

init_user:
    path:     /{_locale}/init/user
    controller: App\Controller\InitController::userAction
    requirements:
        _locale: '%locales%'

# SecurityController

login_check:
    path:     /login_check

login:
    path:     /{_locale}/login
    controller: App\Controller\SecurityController::loginAction
    requirements:
        _locale: '%locales%'

logout:
    path:     /logout

# AdminController

admin_app:
    path:     /admin_app
    controller: App\Controller\AdminController::indexAction

# fallback without locale

index_fallback:
    path:     /
    controller: App\Controller\StartController::indexAction

aliases_fallback:
    path:     /alias
    controller: App\Controller\StartController::aliasAction

openpgp_fallback:
    path:     /openpgp
    controller: App\Controller\StartController::openPgpAction

vouchers_fallback:
    path:     /voucher
    controller: App\Controller\StartController::voucherAction

account_fallback:
    path:     /account
    controller: App\Controller\StartController::accountAction

alias_delete_fallback:
    path:     /alias/delete/{aliasId}
    controller: App\Controller\DeleteController::deleteAliasAction

user_delete_fallback:
    path:     /user/delete
    controller: App\Controller\DeleteController::deleteUserAction

openpgp_delete_fallback:
    path:     /openpgp/delete
    controller: App\Controller\DeleteController::deleteOpenPgpAction

register_fallback:
    path:     /register
    controller: App\Controller\RegistrationController::registerAction

register_recovery_token_fallback:
    path:     /register/recovery_token
    controller: App\Controller\RegistrationController::registerRecoveryTokenAckAction

register_welcome_fallback:
    path:     /register/welcome
    controller: App\Controller\RegistrationController::welcomeAction

register_voucher_fallback:
    path:     /register/{voucher}
    controller: App\Controller\RegistrationController::registerAction

recovery_fallback:
    path:     /recovery
    controller: App\Controller\RecoveryController::recoveryProcessAction

recovery_reset_password_fallback:
    path:     /recovery/reset_password
    controller: App\Controller\RecoveryController::recoveryResetPasswordAction

recovery_recovery_token_ack_fallback:
    path:     /recovery/recovery_token/ack
    controller: App\Controller\RecoveryController::recoveryRecoveryTokenAckAction

user_recovery_token_fallback:
    path:     /user/recovery_token
    controller: App\Controller\RecoveryController::recoveryTokenAction

user_recovery_token_ack_fallback:
    path:     /user/recovery_token/ack
    controller: App\Controller\RecoveryController::recoveryTokenAckAction

init_fallback:
    path:     /init
    controller: App\Controller\InitController::indexAction

init_user_fallback:
    path:     /{_locale}/init/user
    controller: App\Controller\InitController::userAction

login_fallback:
    path:     /login
    controller: App\Controller\SecurityController::loginAction
